create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique not null,
  customer_name text not null,
  customer_email text not null,
  product_id text,
  product_name text not null,
  currency text not null,
  amount numeric(12,2) not null,
  payment_method text not null,
  payment_status text not null default 'pending',
  provider_order_id text,
  provider_session_id text,
  payment_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_email_idx on public.orders(customer_email);
create index if not exists orders_provider_session_idx on public.orders(provider_session_id);
create index if not exists orders_provider_order_idx on public.orders(provider_order_id);

alter table public.orders enable row level security;

-- Serverless functions use the Supabase service-role key, so no public policy is needed.
-- Never expose SUPABASE_SERVICE_ROLE_KEY in browser code.

-- Extra fields used by the storefront/admin order view.
alter table public.orders add column if not exists original_price numeric(12,2);
alter table public.orders add column if not exists discount numeric(12,2) default 0;
alter table public.orders add column if not exists promo_code text;
alter table public.orders add column if not exists download_status text;
